import React from "react";
import {
  Monitor,
  Globe,
  Radio,
  Building2,
  BookOpen,
  Cog,
  TrendingUp,
  FlaskConical,
  Bot,
  Shield,
  Cloud,
  BarChart3,
  Rocket,
  GraduationCap,
  Lightbulb,
  Trophy,
  Calendar,
  Presentation,
  Factory,
  Brain,
  Code2,
  Binary,
  Database,
  Palette,
  Coffee,
  Briefcase,
  Cpu,
  Award,
  Landmark,
  Satellite,
  Zap,
  Plug,
  Wifi,
  Wrench,
  Sliders,
  Milestone,
  Triangle,
  Droplet,
  Waves,
  Gem,
  Thermometer,
  Settings,
  Car,
  Target,
  Search,
  ShoppingCart,
  Atom,
  MessageSquare,
  Puzzle,
  Smartphone,
  Lock,
  Handshake
} from "lucide-react";

const EMOJI_MAP = {
  // Main department icons
  "💻": Monitor,
  "🌐": Globe,
  "📡": Radio,
  "🏗️": Building2,
  "📚": BookOpen,
  "⚙️": Cog,
  "📈": TrendingUp,
  "🔬": FlaskConical,

  // Emerging branches and general
  "🤖": Bot,
  "🛡️": Shield,
  "☁️": Cloud,
  "📊": BarChart3,
  "🚀": Rocket,

  // Chip and feature icons
  "🎓": GraduationCap,
  "💡": Lightbulb,
  "🏆": Trophy,
  "📅": Calendar,
  "👨‍🏫": Presentation,
  "🏭": Factory,
  "🧠": Brain,
  "🐍": Code2, // Python representation
  "🖥️": Monitor,
  "🧮": Binary,
  "🗄️": Database,
  "🎨": Palette,
  "☕": Coffee,
  "💼": Briefcase,
  "📻": Radio,
  "📟": Cpu,
  "🏅": Award,
  "🏛️": Landmark,
  "🛰️": Satellite,
  "⚡": Zap,
  "💾": Cpu,
  "🔌": Plug,
  "📶": Wifi,
  "🔦": Lightbulb,
  "🛠️": Wrench,
  "🎚️": Sliders,
  "🌉": Milestone, // Fallback for Bridge
  "📐": Triangle,
  "👨‍🎓": GraduationCap,
  "💧": Droplet,
  "🌊": Waves,
  "🪨": Gem, // Fallback for Soil / Rock
  "🔧": Wrench,
  "🌡️": Thermometer,
  "🔩": Settings, // Fallback for Nut / Bolt
  "🚗": Car,
  "🎯": Target,
  "🔍": Search,
  "🏦": Landmark,
  "🛒": ShoppingCart,
  "⚛️": Atom,
  "📖": BookOpen,
  "🗣️": MessageSquare,
  "🧪": FlaskConical,
  "🧩": Puzzle,
  "📱": Smartphone,
  "🔒": Lock,
  "🤝": Handshake,
};

export default function EmojiToIcon({ emoji, className = "", size = 24, ...props }) {
  const IconComponent = EMOJI_MAP[emoji];
  if (IconComponent) {
    return <IconComponent className={className} size={size} {...props} />;
  }
  return <span className={className} {...props}>{emoji}</span>;
}
